# START / SELECT / BACK はスコープ外、シンプル優先
names = [
    "弱",   # "A",
    "中",   # "B",
    "必",   # "X",
    "投",   # "Y",
    "なし",  # "LB",
    "なし",  # "RB",
    "",    # "",
    "",    # "",
    "DI",  # "LS",
    "ア",  # "RS",
    "",    # "",
    "DP",  # "LT",
    "",    # "",
    "強",  # "RT",
]

plus = " + "

none_word = "なし" # 全ボタン離しのチェック処理用
