names = [
    "左下",
    "下",
    "右下",
    "左",
    "ニュートラル",
    "右",
    "左上",
    "上",
    "右上",
]

# 斜め上入力をチェックするとき、真上入力したら失敗とみなし、横入力は「成功ではないが、成功まであと一歩なので、失敗ではなくノーカン扱い」とする用
[[no_count_names]]
success  = "右上"
no_count = ["右"] # 上だけの場合はNG。斜めジャンプしようとして垂直ジャンプしたということなので。

[[no_count_names]]
success  = "左上"
no_count = ["左"] # 上だけの場合はNG。斜めジャンプしようとして垂直ジャンプしたということなので。

[[no_count_names]]
success  = "右下"
no_count = ["右", "下"] # 下は許容する。垂直ジャンプと違って取り返しがつくので。

[[no_count_names]]
success  = "左下"
no_count = ["左", "下"] # 下は許容する。垂直ジャンプと違って取り返しがつくので。
